### ISSUE TITLE
os.chmod python 3.5

### ISSUE THREAD

**Issue by waterh** [yhekma/ansible_extra#4]
I found using python 3.5. returns an error on the line 120 in db2 : " os.chmod(tmpfile[1], 0755)"

Noticed for python 3.5 the octal value needs prefix  0o (zero oh)
so changed that line to 
"os.chmod(tmpfile[1], 0o755)" and works now.

**Comment by yhekma** [comment]
fixed in a05fe8ad3f54ce926d8f23bb9b3965b7ef9d0ce1
